main: com.timedfly.TimedFly
name: TimedFly
version: 3.0.0
author: By_Jack
softdepend: [WorldGuard, PlaceholderAPI, TokenManager, ASkyBlock, Vault]
commands:
  timedfly:
    aliases: [tf, timedf]
    usage: /<command>
    description: The main command of TimedFly
  tfly:
    usage: /<command>
    description: Open the fly GUI
